// <auto-generated />
using System;
using Lykke.Service.CurrencyConvertor.MsSqlRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lykke.Service.CurrencyConvertor.MsSqlRepositories.Migrations
{
    [DbContext(typeof(CurrencyContext))]
    [Migration("20190917135018_MoneyType")]
    partial class MoneyType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("currency")
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lykke.Service.CurrencyConvertor.MsSqlRepositories.Entities.CurrencyRateEntity", b =>
                {
                    b.Property<string>("BaseAsset")
                        .HasColumnName("base_asset");

                    b.Property<string>("QuoteAsset")
                        .HasColumnName("quote_asset");

                    b.Property<decimal>("Rate")
                        .HasColumnName("rate");

                    b.HasKey("BaseAsset", "QuoteAsset");

                    b.ToTable("currency_rates");
                });

            modelBuilder.Entity("Lykke.Service.CurrencyConvertor.MsSqlRepositories.Entities.GlobalCurrencyRateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<decimal>("AmountInCurrency")
                        .HasColumnName("amount_in_currency");

                    b.Property<string>("AmountInTokens")
                        .HasColumnName("amount_in_tokens")
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("global_currency_rates");
                });
#pragma warning restore 612, 618
        }
    }
}
